# Generated by Django 2.1.7 on 2019-03-14 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_auto_20190314_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='closed_date',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
